export const SET_TIMESTAMP = 'SET_TIMESTAMP';
export const SET_SEARCHED_TIMESTAMPS = 'SET_SEARCHED_TIMESTAMPS';
export const SET_TIMESTAMPS = 'SET_TIMESTAMPS';
export const ADD_NEW_TIMESTAMP = 'ADD_NEW_TIMESTAMP';
export const SET_TIMESTAMP_DETAIL = 'SET_TIMESTAMP_DETAIL';
export const SET_TIMESTAMP_VALUE = 'SET_TIMESTAMP_VALUE';
export const SET_TIMESTAMP_DEFAULT = 'SET_TIMESTAMP_DEFAULT';