export const SET_OFFICE = 'SET_OFFICE';
export const SET_SEARCHED_OFFICES = 'SET_SEARCHED_OFFICES';
export const SET_OFFICES = 'SET_OFFICES';
export const ADD_NEW_OFFICE = 'ADD_NEW_OFFICE';
export const SET_OFFICE_DETAIL = 'SET_OFFICE_DETAIL';
export const SET_OFFICE_VALUE = 'SET_OFFICE_VALUE';
export const SET_OFFICE_DEFAULT = 'SET_OFFICE_DEFAULT';