export const SET_JOB_POST = 'SET_JOB_POST';
export const SET_SEARCHED_JOB_POSTS = 'SET_SEARCHED_JOB_POSTS';
export const SET_JOB_POSTS = 'SET_JOB_POSTS';
export const ADD_NEW_JOB_POST = 'ADD_NEW_JOB_POST';
export const SET_JOB_POST_DETAIL = 'SET_JOB_POST_DETAIL';
export const SET_JOB_POST_VALUE = 'SET_JOB_POST_VALUE';
export const SET_JOB_POST_DEFAULT = 'SET_JOB_POST_DEFAULT';
export const UPDATE_EDUC_ATTAINMENT_LIST = 'UPDATE_EDUC_ATTAINMENT_LIST';
export const SET_VIEWED_APPLICANT = 'SET_VIEWED_APPLICANT';
export const SET_JP_SEARCH_APPLICANT = 'SET_JP_SEARCH_APPLICANT';
export const UPDATE_TO_BE_ADDED_APPLICANTS = 'UPDATE_TO_BE_ADDED_APPLICANTS';

export const TEMP_APPLICANT_APPLIED = 'TEMP_APPLICANT_APPLIED';
