export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const TOGGLE_ALERT = 'TOGGLE_ALERT';
export const CHANGE_ALERT = 'CHANGE_ALERT';
export const SET_SEARCH_SUGGESTIONS = 'SET_SEARCH_SUGGESTIONS';
export const DISPLAY_SEARCH_RESULT = 'DISPLAY_SEARCH_RESULT';
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';


    