export const SET_ITEM_TYPE = 'SET_ITEM_TYPE';
export const SET_SEARCHED_ITEM_TYPES = 'SET_SEARCHED_ITEM_TYPES';
export const SET_ITEM_TYPES = 'SET_ITEM_TYPES';
export const ADD_NEW_ITEM_TYPE = 'ADD_NEW_ITEM_TYPE';
export const SET_ITEM_TYPE_DETAIL = 'SET_ITEM_TYPE_DETAIL';
export const SET_ITEM_TYPE_VALUE = 'SET_ITEM_TYPE_VALUE';
export const SET_ITEM_TYPE_DEFAULT = 'SET_ITEM_TYPE_DEFAULT';