export const SET_APPLICANT = 'SET_APPLICANT';
export const SET_SEARCHED_APPLICANTS = 'SET_SEARCHED_APPLICANTS';
export const SET_APPLICANTS = 'SET_APPLICANTS';
export const ADD_NEW_APPLICANT = 'ADD_NEW_APPLICANT';
export const SET_APPLICANT_DETAIL = 'SET_APPLICANT_DETAIL';
export const SET_APPLICANT_VALUE = 'SET_APPLICANT_VALUE';
export const SET_APPLICANT_DEFAULT = 'SET_APPLICANT_DEFAULT';