export const SET_ICT_REPAIR_REQUEST = 'SET_ICT_REPAIR_REQUEST';
export const SET_SEARCHED_ICT_REPAIR_REQUESTS = 'SET_SEARCHED_ICT_REPAIR_REQUESTS';
export const SET_ICT_REPAIR_REQUESTS = 'SET_ICT_REPAIR_REQUESTS';
export const ADD_NEW_ICT_REPAIR_REQUEST = 'ADD_NEW_ICT_REPAIR_REQUEST';
export const SET_ICT_REPAIR_REQUEST_DETAIL = 'SET_ICT_REPAIR_REQUEST_DETAIL';
export const SET_ICT_REPAIR_REQUEST_VALUE = 'SET_ICT_REPAIR_REQUEST_VALUE';
export const SET_ICT_REPAIR_REQUEST_DEFAULT = 'SET_ICT_REPAIR_REQUEST_DEFAULT';