export const SET_ICT_APP_ISSUE = 'SET_ICT_APP_ISSUE';
export const SET_SEARCHED_ICT_APP_ISSUES = 'SET_SEARCHED_ICT_APP_ISSUES';
export const SET_ICT_APP_ISSUES = 'SET_ICT_APP_ISSUES';
export const ADD_NEW_ICT_APP_ISSUE = 'ADD_NEW_ICT_APP_ISSUE';
export const SET_ICT_APP_ISSUE_DETAIL = 'SET_ICT_APP_ISSUE_DETAIL';
export const SET_ICT_APP_ISSUE_VALUE = 'SET_ICT_APP_ISSUE_VALUE';
export const SET_ICT_APP_ISSUE_DEFAULT = 'SET_ICT_APP_ISSUE_DEFAULT';